"""
Deterministic schema discovery from raw sample data.

This is the non-AI half of `structifact discover`: given a raw data
file (currently CSV), infer column names, likely types, nullability,
and a "looks unique in this sample" hint for each column.

This module never touches an LLM and never produces a DatasetSpec
directly. It produces a DiscoveredDataset — a draft — which is
rendered as a YAML file for a human to review. Nothing here is
treated as authoritative metadata; see `render_draft_yaml()`.
"""

import csv
import os
from dataclasses import dataclass, field
from typing import List

from .types import infer_type_from_values


@dataclass
class DiscoveredField:
    name: str
    inferred_type: str
    sample_count: int
    null_count: int
    looks_unique: bool

    @property
    def nullable(self) -> bool:
        return self.null_count > 0


@dataclass
class DiscoveredDataset:
    name: str
    source_path: str
    row_count: int
    fields: List[DiscoveredField] = field(default_factory=list)


def discover_csv(path: str, sample_size: int = 100) -> DiscoveredDataset:
    """
    Read a raw CSV file (real data rows, not a metadata spec) and
    infer a draft schema from up to `sample_size` rows.
    """
    with open(path, newline="") as csvfile:
        reader = csv.DictReader(csvfile)

        if reader.fieldnames is None:
            raise ValueError(f"No header row found in {path}")

        columns = {name: [] for name in reader.fieldnames}

        row_count = 0
        for row in reader:
            row_count += 1

            if row_count <= sample_size:
                for name in reader.fieldnames:
                    columns[name].append(row.get(name, ""))

    fields = []
    for name, values in columns.items():
        non_empty = [v for v in values if v is not None and v.strip() != ""]

        fields.append(
            DiscoveredField(
                name=name,
                inferred_type=infer_type_from_values(values),
                sample_count=len(values),
                null_count=len(values) - len(non_empty),
                looks_unique=(
                    len(non_empty) > 0
                    and len(set(non_empty)) == len(non_empty)
                ),
            )
        )

    dataset_name = os.path.splitext(os.path.basename(path))[0]

    return DiscoveredDataset(
        name=dataset_name,
        source_path=path,
        row_count=row_count,
        fields=fields,
    )


def render_draft_yaml(discovered: DiscoveredDataset) -> str:
    """
    Render a DiscoveredDataset as a draft YAML file matching
    Structifact's dataset contract — clearly marked as a draft that
    requires human review before it's real metadata.
    """
    lines = [
        "# DRAFT metadata generated by `structifact discover`.",
        "#",
        "# This is a suggestion based on sampled data, not verified",
        "# metadata. Review every field and description below, fix",
        "# anything wrong, then run `structifact validate` on this",
        "# file yourself before treating it as real.",
        "#",
        f"# Source: {discovered.source_path}",
        f"# Sampled {min(discovered.row_count, 100)} of {discovered.row_count} rows.",
        "",
        "dataset:",
        f"  name: {discovered.name}",
        "  description: TODO — describe this dataset",
        "",
        "fields:",
    ]

    for f in discovered.fields:
        lines.append(f"  - name: {f.name}")
        lines.append(f"    type: {f.inferred_type}")

        hint_parts = [f"sampled {f.sample_count} value(s)"]
        if f.null_count:
            hint_parts.append(f"{f.null_count} blank")
        if f.looks_unique and not f.nullable:
            hint_parts.append("all sampled values unique — possible key")
        if f.inferred_type == "unknown":
            hint_parts.append("could not infer a type — check manually")

        lines.append(f"    description: TODO  # {', '.join(hint_parts)}")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"
